### ISSUE TITLE
Not all functions are parsed from a cbf file

### ISSUE THREAD

**Issue by KT819GM** [jglim/CaesarSuite#44]
Hello, in general some `cbf` files for older cars have `DiagJob` field which contains access unlock functions, making seed calculation unnecessary. As an example Smart For Two W451 have almost all cbf's with these functions available. Being not a programmer I can't contribute to this, but I did checked few times with different cbf's and compared end results against `vedi*` and CaesarSuite. If this project is still developed I could provide exact file with screenshots.

**Comment by jglim** [comment]
Hello KT819GM,

Thanks for taking time to write about this issue.

You are correct that the DiagJob contained within CBF files may have the ability to automatically unlock a target. However, DiagJobs are able to do this only because they call on an embedded, compiled script within the CBF. The DiagJob itself does not contain meaningful information; instead, the heavy lifting is done by the script. In the below example screenshot, notice that the bytes for diagjobs (prefixed by `DJ_`) are either empty or useless `00`s.

![image](https://user-images.githubusercontent.com/1116555/153788484-b7c84fd0-9943-4e62-a5d5-a4377b281746.png)


The script interpreter/vm is fairly complex and difficult to implement correctly, so at this time, this project does not have the ability to execute scripts. This means that out of the box, Caesar/Diogenes does not have the ability to generate seed keys. Instead, this task is deferred to [UnlockECU](https://github.com/jglim/UnlockECU/), where many algos are reverse-engineered and re-implemented.

*The official tools (e.g. DTS/Vedi) naturally have no difficulties in executing those scripts, so they do not need an additional ECU unlocking tool.

**Comment by KT819GM** [comment]
Hello,
Thank you for an explanation, couldn't be written more clearly.
